export const SYSTEM_ARCHIVE_PORTABILITY_CLASSES = [
  "portable_authority",
  "portable_normalized",
  "rebuildable",
  "operational",
  "security_authority",
  "deployment_configuration"
] as const;

export type PortabilityClass = typeof SYSTEM_ARCHIVE_PORTABILITY_CLASSES[number];

/** Every table created by the current migrations has one deliberate export treatment. */
export const SYSTEM_ARCHIVE_TABLE_CLASSIFICATIONS = {
  activity_events: "portable_authority",
  api_admission_buckets: "operational",
  api_admission_leases: "operational",
  archive_previews: "operational",
  asset_derivatives: "rebuildable",
  asset_generation_contexts: "portable_normalized",
  asset_library_entries: "portable_normalized",
  asset_metadata_backfill_jobs: "operational",
  asset_metadata_backfill_publications: "operational",
  asset_mutation_idempotency: "operational",
  asset_publication_content_arbitrations: "operational",
  asset_publication_identities: "operational",
  asset_publication_library_initializations: "operational",
  asset_publication_request_contexts: "operational",
  asset_publication_request_derivatives: "operational",
  asset_publication_request_references: "operational",
  asset_publication_request_results: "operational",
  asset_publication_request_sources: "operational",
  asset_publication_requests: "operational",
  asset_references: "portable_authority",
  assets: "portable_authority",
  campaign_canonical_facts: "portable_authority",
  campaign_character_profile_edits: "portable_authority",
  campaign_illustration_configs: "portable_authority",
  campaign_memory_configs: "portable_authority",
  campaign_state: "portable_authority",
  campaign_state_edits: "portable_authority",
  campaign_world_migrations: "portable_authority",
  campaign_world_transfers: "portable_authority",
  campaigns: "portable_authority",
  chronicle_chunk_jobs: "operational",
  chronicle_jobs: "operational",
  chronicle_memories: "portable_authority",
  chronicle_memory_chunks: "rebuildable",
  chronicle_query_embedding_cache: "rebuildable",
  chronicle_retrieval_candidates: "rebuildable",
  chronicle_retrieval_runs: "rebuildable",
  durable_filesystem_candidate_authorities: "operational",
  durable_filesystem_descriptors: "operational",
  durable_filesystem_operations: "operational",
  durable_filesystem_prewrite_nodes: "operational",
  generation_attempts: "operational",
  generation_jobs: "operational",
  illustration_backfill_jobs: "operational",
  illustration_match_candidates: "rebuildable",
  illustration_prompt_jobs: "operational",
  illustration_resolution_jobs: "operational",
  image_job_asset_publications: "operational",
  image_jobs: "operational",
  import_progress_status: "operational",
  imports: "portable_authority",
  model_chains: "operational",
  portable_export_artifacts: "operational",
  portable_import_asset_publications: "operational",
  portable_import_asset_reservation_intents: "operational",
  portable_import_normalized_asset_contexts: "operational",
  portable_import_normalized_asset_publications: "operational",
  portable_import_normalized_asset_references: "operational",
  portable_import_normalized_asset_sources: "operational",
  portable_import_operations: "operational",
  portable_import_work: "operational",
  portable_staged_inputs: "operational",
  private_filesystem_delivery_grants: "security_authority",
  private_finalized_asset_delivery_grants: "security_authority",
  private_legacy_asset_read_capabilities: "security_authority",
  prompt_template_overrides: "portable_authority",
  provider_cost_events: "portable_authority",
  provider_profiles: "portable_normalized",
  summary_checkpoints: "portable_authority",
  turn_illustration_segment_assets: "portable_authority",
  turn_illustration_segments: "portable_authority",
  turn_illustration_sets: "portable_authority",
  turn_input_classifications: "portable_authority",
  turn_narration_corrections: "portable_authority",
  turns: "portable_authority",
  users: "portable_authority",
  world_drafts: "portable_authority",
  world_generation_progress: "operational",
  world_share_links: "security_authority",
  world_versions: "portable_authority",
  worlds: "portable_authority"
} as const satisfies Record<string, PortabilityClass>;
