import { buildCanonicalChronicleFacts } from "../../domain/src/chronicle-memory-helpers.js";

type Snapshot = Readonly<Record<string, unknown>>;

function stringValues(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((candidate): candidate is string => typeof candidate === "string")
    : [];
}

function canonicalFactUpdates(snapshot: Snapshot) {
  return Array.isArray(snapshot.canonicalFactUpdates)
    ? snapshot.canonicalFactUpdates.flatMap((candidate) => {
      if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) return [];
      const update = candidate as Record<string, unknown>;
      return typeof update.content === "string"
        ? [{ content: update.content, supersedesFactIds: stringValues(update.supersedesFactIds) }]
        : [];
    })
    : [];
}

function projectedFactIds(snapshot: Snapshot, campaignId: string, turnId: string): string[] {
  return buildCanonicalChronicleFacts({
    campaignId,
    turnId,
    canonicalFacts: stringValues(snapshot.canonicalFacts),
    canonicalFactUpdates: canonicalFactUpdates(snapshot),
    entityCatalog: []
  }).map((fact) => fact.id);
}

/**
 * Reassigns explicit correction fact identities for a destination campaign.
 * The supplied map is then shared with accepted-turn reference remapping.
 */
export function remapCorrectionSnapshotFactIds(
  snapshot: Snapshot,
  factIds: Map<string, string>,
  createId: () => string,
): Record<string, unknown> {
  if (!Array.isArray(snapshot.canonicalFacts)) return { ...snapshot };
  return {
    ...snapshot,
    canonicalFacts: snapshot.canonicalFacts.map((candidate) => {
      if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) return candidate;
      const fact = candidate as Record<string, unknown>;
      if (typeof fact.id !== "string") return { ...fact };
      const destinationId = factIds.get(fact.id) ?? createId();
      factIds.set(fact.id, destinationId);
      return { ...fact, id: destinationId };
    })
  };
}

/**
 * Registers the deterministic destination identities generated by an accepted
 * snapshot before any correction snapshots refer to them.
 */
export function preseedAcceptedTurnSnapshotFactIds(
  snapshot: Snapshot,
  input: Readonly<{
    sourceCampaignId: string;
    sourceTurnId: string;
    destinationCampaignId: string;
    destinationTurnId: string;
    factIds: Map<string, string>;
  }>,
): void {
  const sourceFactIds = projectedFactIds(snapshot, input.sourceCampaignId, input.sourceTurnId);
  const destinationFactIds = projectedFactIds(snapshot, input.destinationCampaignId, input.destinationTurnId);
  sourceFactIds.forEach((sourceId, index) => {
    const destinationId = destinationFactIds[index];
    if (destinationId) input.factIds.set(sourceId, destinationId);
  });
}

/**
 * Leaves accepted snapshots intact apart from the destination-local fact references
 * required by their canonicalFactUpdates. The source snapshot is never mutated.
 */
export function remapAcceptedTurnSnapshotFactReferences(
  snapshot: Snapshot,
  input: Readonly<{
    sourceCampaignId: string;
    sourceTurnId: string;
    destinationCampaignId: string;
    destinationTurnId: string;
    factIds: Map<string, string>;
  }>,
): Record<string, unknown> {
  preseedAcceptedTurnSnapshotFactIds(snapshot, input);
  if (!Array.isArray(snapshot.canonicalFactUpdates)) return { ...snapshot };
  return {
    ...snapshot,
    canonicalFactUpdates: snapshot.canonicalFactUpdates.map((candidate) => {
      if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) return candidate;
      const update = candidate as Record<string, unknown>;
      if (!Array.isArray(update.supersedesFactIds)) return { ...update };
      return {
        ...update,
        supersedesFactIds: update.supersedesFactIds.map((id) => (
          typeof id === "string" ? input.factIds.get(id) ?? id : id
        ))
      };
    })
  };
}
