import { canonicalFactDeduplicationKey } from "../../domain/src/canonical-facts.js";
import { buildCanonicalChronicleFacts } from "../../domain/src/chronicle-memory-helpers.js";

type Snapshot = Readonly<Record<string, unknown>>;

function stringValues(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((candidate): candidate is string => typeof candidate === "string")
    : [];
}

function canonicalFactUpdates(snapshot: Snapshot) {
  return Array.isArray(snapshot.canonicalFactUpdates)
    ? snapshot.canonicalFactUpdates.flatMap((candidate) => {
      if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) return [];
      const update = candidate as Record<string, unknown>;
      return typeof update.content === "string"
        ? [{ content: update.content, supersedesFactIds: stringValues(update.supersedesFactIds) }]
        : [];
    })
    : [];
}

function projectedFacts(snapshot: Snapshot, campaignId: string, turnId: string) {
  return buildCanonicalChronicleFacts({
    campaignId,
    turnId,
    canonicalFacts: Array.isArray(snapshot.canonicalFacts) ? snapshot.canonicalFacts.flatMap((value) => typeof value === "string" ? [value]
      : value && typeof value === "object" && "content" in value && typeof value.content === "string" ? [value.content] : []) : [],
    canonicalFactUpdates: canonicalFactUpdates(snapshot),
    entityCatalog: []
  });
}

/**
 * Reassigns explicit correction fact identities for a destination campaign.
 * The supplied map is then shared with accepted-turn reference remapping.
 */
export function remapCorrectionSnapshotFactIds(
  snapshot: Snapshot,
  factIds: Map<string, string>,
  createId: () => string,
): Record<string, unknown> {
  if (!Array.isArray(snapshot.canonicalFacts)) return { ...snapshot };
  return {
    ...snapshot,
    canonicalFacts: snapshot.canonicalFacts.map((candidate) => {
      if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) return candidate;
      const fact = candidate as Record<string, unknown>;
      if (typeof fact.id !== "string") return { ...fact };
      const destinationId = factIds.get(fact.id) ?? createId();
      factIds.set(fact.id, destinationId);
      return { ...fact, id: destinationId };
    })
  };
}

/**
 * Registers the deterministic destination identities generated by an accepted
 * snapshot before any correction snapshots refer to them.
 */
export function preseedAcceptedTurnSnapshotFactIds(
  snapshot: Snapshot,
  input: Readonly<{
    sourceCampaignId: string;
    sourceTurnId: string;
    destinationCampaignId: string;
    destinationTurnId: string;
    factIds: Map<string, string>;
  }>,
): void {
  const sourceFacts = projectedFacts(snapshot, input.sourceCampaignId, input.sourceTurnId);
  const destinationFacts = projectedFacts(snapshot, input.destinationCampaignId, input.destinationTurnId);
  sourceFacts.forEach((sourceFact, index) => {
    const destinationId = destinationFacts[index]?.id;
    if (!destinationId) return;
    input.factIds.set(sourceFact.id, destinationId);
    for (const value of Array.isArray(snapshot.canonicalFacts) ? snapshot.canonicalFacts : []) {
      if (value && typeof value === "object" && typeof value.id === "string" && typeof value.content === "string"
        && canonicalFactDeduplicationKey(value.content) === canonicalFactDeduplicationKey(sourceFact.content)
        && !input.factIds.has(value.id)) input.factIds.set(value.id, destinationId);
    }
  });
}

/**
 * Leaves accepted snapshots intact apart from the destination-local fact references
 * required by their canonicalFactUpdates. The source snapshot is never mutated.
 */
export function remapAcceptedTurnSnapshotFactReferences(
  snapshot: Snapshot,
  input: Readonly<{
    sourceCampaignId: string;
    sourceTurnId: string;
    destinationCampaignId: string;
    destinationTurnId: string;
    factIds: Map<string, string>;
  }>,
): Record<string, unknown> {
  preseedAcceptedTurnSnapshotFactIds(snapshot, input);
  const remappedSnapshot = {
    ...snapshot,
    ...(Array.isArray(snapshot.canonicalFacts) ? { canonicalFacts: snapshot.canonicalFacts.map((value) => {
      if (!value || typeof value !== "object" || Array.isArray(value)) return value;
      return { ...value, id: typeof value.id === "string" ? input.factIds.get(value.id) ?? null : null };
    }) } : {})
  };
  if (!Array.isArray(snapshot.canonicalFactUpdates)) return remappedSnapshot;
  return {
    ...remappedSnapshot,
    canonicalFactUpdates: snapshot.canonicalFactUpdates.map((candidate) => {
      if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) return candidate;
      const update = candidate as Record<string, unknown>;
      if (!Array.isArray(update.supersedesFactIds)) return { ...update };
      return {
        ...update,
        supersedesFactIds: update.supersedesFactIds.flatMap((id) => {
          const destinationId = typeof id === "string" ? input.factIds.get(id) : undefined;
          return destinationId ? [destinationId] : [];
        })
      };
    })
  };
}
