/** Bounded JSONB extraction for saved response-contract status. */
export function generationResponseFormatProjection(privateColumn: string): string {
  const text = (path: string) => `${privateColumn} #>> '{${path}}'`;
  const value = (path: string) => `${privateColumn} #> '{${path}}'`;
  const selected = `COALESCE(${value("frozenResponseContracts,contracts,story:stream")}, ${value("frozenResponseContracts,contracts,story:nonstream")})`;
  const latest = `${privateColumn} -> 'responseContractInvocations' -> -1`;
  return `jsonb_build_object(
    'queuedResponsePolicy', CASE WHEN ${value("queuedResponsePolicy")} IS NULL THEN NULL ELSE jsonb_build_object('version', ${text("queuedResponsePolicy,version")}, 'policy', ${text("queuedResponsePolicy,policy")}, 'model', ${text("queuedResponsePolicy,model")}) END,
    'frozenResponseContracts', CASE WHEN ${selected} IS NULL THEN NULL ELSE jsonb_build_object('contracts', jsonb_build_object(
      'story:stream', CASE WHEN ${value("frozenResponseContracts,contracts,story:stream")} IS NULL THEN NULL ELSE jsonb_build_object('mode', ${text("frozenResponseContracts,contracts,story:stream,mode")}, 'operation', ${text("frozenResponseContracts,contracts,story:stream,operation")}, 'streaming', CASE WHEN ${text("frozenResponseContracts,contracts,story:stream,streaming")} IN ('true','false') THEN ${text("frozenResponseContracts,contracts,story:stream,streaming")}::boolean ELSE NULL END, 'schemaVersion', ${text("frozenResponseContracts,contracts,story:stream,schemaVersion")}, 'schemaHash', ${text("frozenResponseContracts,contracts,story:stream,schemaHash")}) END,
      'story:nonstream', CASE WHEN ${value("frozenResponseContracts,contracts,story:nonstream")} IS NULL THEN NULL ELSE jsonb_build_object('mode', ${text("frozenResponseContracts,contracts,story:nonstream,mode")}, 'operation', ${text("frozenResponseContracts,contracts,story:nonstream,operation")}, 'streaming', CASE WHEN ${text("frozenResponseContracts,contracts,story:nonstream,streaming")} IN ('true','false') THEN ${text("frozenResponseContracts,contracts,story:nonstream,streaming")}::boolean ELSE NULL END, 'schemaVersion', ${text("frozenResponseContracts,contracts,story:nonstream,schemaVersion")}, 'schemaHash', ${text("frozenResponseContracts,contracts,story:nonstream,schemaHash")}) END)) END,
    'responseContractInvocations', CASE WHEN jsonb_typeof(${privateColumn} -> 'responseContractInvocations') = 'array' AND jsonb_typeof(${latest}) = 'object' THEN jsonb_build_array(jsonb_build_object(
      'version', ${latest} ->> 'version', 'invocationKey', ${latest} ->> 'invocationKey', 'request', jsonb_build_object('mode', ${latest} #>> '{request,mode}', 'operation', ${latest} #>> '{request,operation}', 'streaming', CASE WHEN ${latest} #>> '{request,streaming}' IN ('true','false') THEN (${latest} #>> '{request,streaming}')::boolean ELSE NULL END, 'requestedModel', ${latest} #>> '{request,requestedModel}', 'schemaVersion', ${latest} #>> '{request,schemaVersion}', 'schemaHash', ${latest} #>> '{request,schemaHash}'),
      'response', CASE WHEN jsonb_typeof(${latest} -> 'response') = 'object' THEN jsonb_build_object('returnedModel', ${latest} #>> '{response,returnedModel}', 'returnedProviderRoute', ${latest} #>> '{response,returnedProviderRoute}', 'diagnosticCode', ${latest} #>> '{response,diagnosticCode}') ELSE NULL END)) ELSE '[]'::jsonb END
  )`;
}
